{
 "title": "Mon Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temps passé à Commander",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=\"restaurant-staff-order\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"}[1m])) \n/ \nsum(rate(http_server_requests_seconds_count{container=\"restaurant-staff-order\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"}[1m]))",
     "legendFormat": "AVG Response Time"
    },
    {
     "expr": "max(http_server_requests_seconds_max{container=\"restaurant-staff-order\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"})",
     "legendFormat": "MAX Response Time"
    }
   ]
  },
  {
   "title": "Temps passé à l'Accueil",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=\"restaurant-staff-enter\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"}[1m])) \n/ \nsum(rate(http_server_requests_seconds_count{container=\"restaurant-staff-enter\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"}[1m]))\n",
     "legendFormat": "AVG Response Time"
    },
    {
     "expr": "max(http_server_requests_seconds_max{container=\"restaurant-staff-enter\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"})",
     "legendFormat": "MAX Response Time"
    }
   ]
  },
  {
   "title": "Temps passé au Paiement",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=\"restaurant-staff-pay\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"}[1m])) \n/ \nsum(rate(http_server_requests_seconds_count{container=\"restaurant-staff-pay\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"}[1m]))\n",
     "legendFormat": "AVG Response Time"
    },
    {
     "expr": "max(http_server_requests_seconds_max{container=\"restaurant-staff-pay\", namespace=\"$namespace\", uri!~\"/q/metrics|/health|root\"})",
     "legendFormat": "MAX Response Time"
    }
   ]
  },
  {
   "title": "Nombre d'employés par poste",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}