{
 "title": "Mon Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$cluster\", namespace=~\".*restaurant.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temps passé à l'Accueil",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=\"restaurant-staff-enter\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m]))\n/ \nsum(rate(http_server_requests_seconds_count{container=\"restaurant-staff-enter\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m]))\n* 15\n",
     "legendFormat": "AVG Response Time"
    },
    {
     "expr": "max(http_server_requests_seconds_max{container=\"restaurant-staff-enter\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"})\n* 15",
     "legendFormat": "MAX Response Time"
    }
   ]
  },
  {
   "title": "Temps passé à Commander",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=\"restaurant-staff-order\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m])) \n/ \nsum(rate(http_server_requests_seconds_count{container=\"restaurant-staff-order\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m]))\n* 15",
     "legendFormat": "AVG Response Time"
    },
    {
     "expr": "max(http_server_requests_seconds_max{container=\"restaurant-staff-order\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"})\n* 15",
     "legendFormat": "MAX Response Time"
    }
   ]
  },
  {
   "title": "Temps passé au Paiement",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=\"restaurant-staff-pay\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m])) \n/ \nsum(rate(http_server_requests_seconds_count{container=\"restaurant-staff-pay\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m]))\n* 15\n",
     "legendFormat": "AVG Response Time"
    },
    {
     "expr": "max(http_server_requests_seconds_max{container=\"restaurant-staff-pay\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"})\n* 15",
     "legendFormat": "MAX Response Time"
    }
   ]
  },
  {
   "title": "Nombre d'employés par poste",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\", container=~\"restaurant.*\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\", container=~\"restaurant.*\"})",
     "legendFormat": "Employés"
    }
   ]
  },
  {
   "title": "Temps passé à interragir avec le Restaurant",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=~\"restaurant-staff-.*\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m]) ) by (container)\n/ \nsum(rate(http_server_requests_seconds_count{container=~\"restaurant-staff-.*\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}[1m])) by (container)\n* 15",
     "legendFormat": "avg-{{container}}"
    },
    {
     "expr": "max(http_server_requests_seconds_max{container=~\"restaurant-staff-.*\", namespace=\"$namespace\", uri!~\"/q/metrics|/q/health|root\"}) by (container)\n* 15",
     "legendFormat": "max-{{container}}"
    }
   ]
  },
  {
   "title": "Utilisation CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"restaurant.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Utilisation Mémoire",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=~\"restaurant.*\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}