apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  version: v1beta1
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  versionPriority: 100
  service:
    name: prometheus-adapter
    namespace: monitoring
    port: 443







