apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: restaurant-staff-pay-hpa
  namespace: restaurant
  labels:
    app: restaurant-staff-pay
    app.kubernetes.io/name: restaurant-staff
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: pay
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restaurant-staff-pay
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
