apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: restaurant
  labels:
    app: postgres
data:
  POSTGRES_DB: restaurant
  POSTGRES_USER: lhauspie
  POSTGRES_PASSWORD: lhauspie
