apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: restaurant-staff-pay
  namespace: perfect-restaurant
spec:
  scaleTargetRef:
    name: restaurant-staff-pay
  minReplicaCount:  0
  maxReplicaCount:  30
  pollingInterval:  3    # 00m45s in real life
  cooldownPeriod:   30   # 07m30s in real life
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        metricName: http_server_requests_seconds_sum
        query: sum(rate(http_server_requests_seconds_sum{namespace="perfect-restaurant", container="restaurant-staff-pay", uri="/pay"}[2m])) * 15
        threshold: '120'     # Scale Up if customers wait over 2 minutes
    - type: postgresql
      metadata:
        host: pr-postgres.perfect-restaurant.svc.cluster.local #use the cluster-wide namespace as KEDA lives in a different namespace from your postgres
        port: "5432"
        userName: lhauspie
        passwordFromEnv: PG_PASSWORD # the name of the env var inside scaleTargetRef pod.
        dbName: restaurant
        sslmode: disable
        # Remember the time is divided by 15 for test purpose.
        # So 7 minutes = 1h45 and 5 minutes = 1h00
        # We're looking for activity yesterday in next 5 minutes
        query: |
          SELECT COUNT(1)::decimal
          FROM customerpayment
          WHERE paymenttime >= now() - INTERVAL '1h' + INTERVAL '20s'
            AND paymenttime <= now() - INTERVAL '1h' + INTERVAL '40s'
        targetQueryValue: "6"
        metricName: postgresql-restaurant-staff-enter #optional. Generated value would be `postgresql-restaurant`
    - type: cron
      metadata:
        timezone: Europe/Paris
        start: 10 * * * *
        end: 35 * * * *
        desiredReplicas: "1"
