apiVersion: v1
kind: PersistentVolume
metadata:
  name: pr-postgres-pv-volume
  namespace: perfect-restaurant
  labels:
    type: local
    app: pr-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
