apiVersion: v1
kind: Service
metadata:
  name: pr-postgres
  namespace: perfect-restaurant
  labels:
    app: pr-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: pr-postgres
