build:
	cd enter && make build
	cd order && make build
	cd pay && make build

package:
	cd enter && make package
	cd order && make package
	cd pay && make package

deliver:
	cd enter && make deliver
	cd order && make deliver
	cd pay && make deliver


all:
	cd enter && make all
	cd order && make all
	cd pay && make all
