apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: restaurant-staff-order
  namespace: restaurant
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restaurant-staff-order
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_server_requests_per_second
        target:
          type: AverageValue
          averageValue: 1
