apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
  namespace: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  replicas: 2
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.0.3
          ports:
            - containerPort: 9898

---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
  namespace: podinfo
  labels:
    run: podinfo
spec:
  type: LoadBalancer
  ports:
    - port: 9898
      protocol: TCP
  selector:
    app:  podinfo

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: podinfo
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: podinfo-service
              servicePort: 9898
