apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: restaurant-staff-metrics-monitor
  namespace: perfect-restaurant
  labels:
    name: restaurant-staff
spec:
  endpoints:
    - path: /q/metrics
      interval: 5s
      port: http
      scheme: http
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: restaurant-staff